COMPOSE  := docker compose -f infra/docker-compose.yml
ALEMBIC  := cd backend && alembic
PYTHON   := cd backend && python

.PHONY: up down logs reset seed migrate migration migrate-down

# ── Infrastructure ────────────────────────────────────────────────────────────

## Start all local infra services (postgres, redis, minio) in detached mode
up:
	$(COMPOSE) up -d

## Stop all services (volumes are preserved)
down:
	$(COMPOSE) down

## Tail logs from all infra services (Ctrl-C to exit)
logs:
	$(COMPOSE) logs -f

## Destroy all volumes and recreate everything from scratch
reset:
	$(COMPOSE) down -v --remove-orphans
	$(COMPOSE) up -d

# ── Database ──────────────────────────────────────────────────────────────────

## Apply all pending migrations (alembic upgrade head)
migrate:
	$(ALEMBIC) upgrade head

## Create a new autogenerated migration  — usage: make migration msg="add groups table"
migration:
	$(ALEMBIC) revision --autogenerate -m "$(msg)"

## Roll back the last applied migration (alembic downgrade -1)
migrate-down:
	$(ALEMBIC) downgrade -1

## Populate the database with local dev fixtures
seed:
	$(PYTHON) -m app.db.seed
